var news = {
    "events":[
        {
            "start_date":{
                "year":2017,
                "month":4,
                "day":20
            },
            "text":{
                "headline":"天舟一号货运飞船成功发射"
            }
        },
        {
            "start_date":{
                "year":2017,
                "month":5,
                "day":5
            },
            "text":{
                "headline":"第一架国产大飞机C919首飞成功"
            }
        },
        {
            "start_date":{
                "year":2017,
                "month":5,
                "day":18
            },
            "text":{
                "headline":"可燃冰试采成功"
            }
        },
        {
            "start_date":{
                "year":2017,
                "month":6,
                "day":15
            },
            "text":{
                "headline":"首颗X射线天文卫星成功发射"
            }
        },
        {
            "start_date":{
                "year":2017,
                "month":6,
                "day":26
            },
            "text":{
                "headline":"标准动车组“复兴号”发车"
            }
        },
        {
            "start_date":{
                "year":2017,
                "month":6,
                "day":28
            },
            "text":{
                "headline":"055万吨级驱逐舰首舰正式下水"
            }
        },
        {
            "start_date":{
                "year":2017,
                "month":6,
                "day":28
            },
            "text":{
                "headline":"宜宾金沙江公铁两用特大桥主拱桥合龙"
            }
        },
        {
            "start_date":{
                "year":2017,
                "month":7,
                "day":2
            },
            "text":{
                "headline":"长征五号遥二火箭发射失利",
                "text": "http://weibo.com/3937348351/FayrV38gN?filter=hot&root_comment_id=0&type=comment#_rnd1499171232361"
            }
        }
    ]
}